version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: comfytag-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - comfytag-network

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: comfytag-api
    restart: unless-stopped
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://comfytag-redis:6379
      - REDIS_HOST=comfytag-redis
      - REDIS_PORT=6379
      - PORT=4002
      - MONGO=mongodb://admin:comfytag456@host.docker.internal:27017/?authSource=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ./apps/api/.env
    depends_on:
      - redis
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    networks:
      - comfytag-network

volumes:
  redis_data:

networks:
  comfytag-network:
    driver: bridge
