packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  cpu-features: true
  esbuild: true
  mongodb-memory-server: true
  msgpackr-extract: set this to true or false
  sharp: true
  ssh2: true
  unrs-resolver: true
  yarn: true
